module.exports = {
	LRC_OPENING_FLAG: '~',
	LRC_CLOSING_FLAG: '\\',
	LRC_CMD_TYPE_XPOINT: { id: 'XPOINT', label: 'Crosspoint Control' },
	LRC_CMD_TYPE_LOCK: { id: 'LOCK', label: 'Destination Lock' },
	LRC_CMD_TYPE_PROTECT: { id: 'PROTECT', label: 'Destination Protect' },
	LRC_CMD_TYPE_CHANNELS: { id: 'CHANNELS', label: 'Logical Channel (Level)' },
	LRC_CMD_TYPE_DEST: { id: 'DEST', label: 'Logical Destination' },
	LRC_CMD_TYPE_SRC: { id: 'SRC', label: 'Logical Source' },
	LRC_CMD_TYPE_DBCHANGE: { id: 'DBCHANGE', label: 'Database Change Notification' },
	LRC_CMD_TYPE_CONNECTION: { id: 'CONNECTION', label: 'Connection (Session) Control' },
	LRC_CMD_TYPE_PROTOCOL: { id: 'PROTOCOL', label: 'Protocol Information' },
	LRC_CMD_TYPE_XBUFFER: { id: 'XBUFFER', label: 'Crosspoint Buffer Control' },
	LRC_CMD_TYPE_XDISCONNECT: { id: 'XDISCONNECT', label: 'Disconnect Logical Crosspoint' },
	LRC_CMD_TYPE_XPRESET: { id: 'XPRESET', label: 'Crosspoint Preset' },
	LRC_CMD_TYPE_XSALVO: { id: 'XSALVO', label: 'Crosspoint Salvo' },
	LRC_CMD_TYPES: [
		{ id: 'XPOINT', label: 'Crosspoint Control' },
		{ id: 'LOCK', label: 'Destination Lock' },
		{ id: 'PROTECT', label: 'Destination Protect' },
		{ id: 'CHANNELS', label: 'Logical Channel (Level)' },
		{ id: 'DEST', label: 'Logical Destination' },
		{ id: 'SRC', label: 'Logical Source' },
		{ id: 'DBCHANGE', label: 'Database Change Notification' },
		{ id: 'CONNECTION', label: 'Connection (Session) Control' },
		{ id: 'PROTOCOL', label: 'Protocol Information' },
		{ id: 'XBUFFER', label: 'Crosspoint Buffer Control' },
		{ id: 'XDISCONNECT', label: 'Disconnect Logical Crosspoint' },
		{ id: 'XPRESET', label: 'Crosspoint Preset' },
		{ id: 'XSALVO', label: 'Crosspoint Salvo' },
	],
	LRC_OP_CHANGE_REQUEST: { id: ':', label: 'Change Request' },
	LRC_OP_CHANGE_NOTIFICATION: { id: '!', label: 'Change Notification' },
	LRC_OP_QUERY: { id: '?', label: 'Query' },
	LRC_OP_QUERY_RESPONSE: { id: '%', label: 'Query Response' },
	LRC_OPS: [
		{ id: ':', label: 'Change Request' },
		{ id: '?', label: 'Query' },
	],
	LRC_ARG_TYPE_STRING: '$',
	LRC_ARG_TYPE_NUMERIC: '#',
	LRC_ARG_TYPE_UTF8: '&',
	LRC_ARG_TYPES: ['$', '#', '&'],
	LRC_CMD_TYPE_LOCK_OVERRIDE_USER: -1,
	LRC_CMD_TYPE_XSALVO_FLAGS: [
		{ id: 'TAKE', label: 'Take salvo (default)' },
		{ id: 'PRESET', label: 'Store salvo in the preset buffer' },
		{ id: 'LOCK', label: 'Lock salvo crosspoints after execution' },
		{ id: 'PROTECT', label: 'Protect salvo crosspoints after execution' },
		{ id: 'UNLOCK', label: 'Unlock salvo crosspoints before execution' },
		{ id: 'NOTAKE', label: 'Inhibit crosspoint take' },
	],
	LRC_CMD_TYPE_PROTOCOL_QUERIES: [
		{ id: 'NAME', label: 'Protocol Name' },
		{ id: 'VERSION', label: 'Protocol Version' },
	],
	LRC_CMD_TYPE_DEST_QUERIES: [
		{ id: 'COUNT', label: 'Count of logical destinations in the system' },
		{ id: 'NAME', label: 'Name of destination(s)' },
		{ id: 'CHANNELS', label: 'List of valid channels' },
		{ id: 'PHYSICAL', label: 'Physical location of a channel' },
	],
	LRC_CMD_TYPE_SOURCE_QUERIES: [
		{ id: 'COUNT', label: 'Count of logical sources in the system' },
		{ id: 'NAME', label: 'Name of source(s)' },
		{ id: 'CHANNELS', label: 'List of valid channels' },
		{ id: 'PHYSICAL', label: 'Physical location of a channel' },
	],
}
